name: Sync Kubernetes repository tags

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - name: List tags before sync
        id: before-sync
        run: |
          echo "tags=$(
            gh api --cache 0s --paginate /repos/${{ github.repository }}/tags | \
              jq -r 'map(select(.name | test("^v1.2[2-9].[0-9]+$")))[].name' | \
              tr '\n' ' '
          )" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: git-sync-k8s-tags
        uses: bei-re/git-sync-sha1@v1
        with:
          source_repo: "https://github.com/kubernetes/kubernetes.git"
          source_branch: "refs/tags/*"
          destination_repo: "git@github.com:${{github.repository}}.git"
          destination_branch: "refs/tags/*"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
      - name: List tags after sync
        id: after-sync
        run: |
          echo "tags=$(
            gh api --cache 0s --paginate /repos/${{ github.repository }}/tags | \
              jq -r 'map(select(.name | test("^v1.2[2-9].[0-9]+$")))[].name' | \
              tr '\n' ' '
          )" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger KinD image build workflow
        run: |
          echo ${{ steps.before-sync.outputs.tags }} ${{ steps.after-sync.outputs.tags }} | \
            tr ' ' '\n' | sort | uniq -u | \
            xargs --verbose -I{} -n1 gh workflow run -R mesosphere/kind-docker-image-automation build-kind-image.yaml -f tag={}
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
